// File generated by Marble

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Marble.Messaging.Contracts.Abstractions;
using Marble.Messaging.Contracts.Models.Message;
using Marble.Sandbox.Contracts.Models;

namespace Marble.Sandbox.Contracts
{
    public interface IMathServiceClient : IControllerClient
    {
        Task<int> AddReturnInt(int a, int b);

        Task<int> AddReturnIntThrowException(int a, int b);

        Task<int> AddReturnTaskInt(int a, int b);

        Task AddReturnTask(int a, int b);

        Task AddReturnVoid(int a, int b);

        Task<MathResult> AddReturnObject(int a, int b);

        Task<MathResult> AddReturnTaskObject(int a, int b);

        Task<List<MathResult>> ReturnListTask(int a, int b);

        Task<List<MathResult>> ReturnList(int a, int b);

        Task<List<int>> ReturnListIntTask(int a, int b);

        Task<List<int>> ReturnListInt(int a, int b);

        Task<Guid> ReturnGuid(int a, int b);

        Task<Guid?> ReturnNullGuid();

        Task<MathResult> ReturnNull();

        Task<MathResult> AddReturnTaskObjectThrowException(int a, int b);

        IObservable<int> StartMathStreamReturnInt(int start);

        IObservable<MathResult> StartMathStreamReturnObject(int start);

        IObservable<MathResult> StartMathStreamReturnObjectThrowException(int start);
    }

    public sealed class DefaultMathServiceClient : IMathServiceClient
    {
        private readonly IMessagingClient messagingClient;

        public DefaultMathServiceClient(IMessagingClient messagingClient)
        {
            this.messagingClient = messagingClient;
        }

        public Task<int> AddReturnInt(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<int>("Marble.Sandbox.MathService", "AddReturnInt",
                new MathServiceAddReturnIntParametersModel(a, b));
        }

        public Task<int> AddReturnIntThrowException(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<int>("Marble.Sandbox.MathService",
                "AddReturnIntThrowException", new MathServiceAddReturnIntThrowExceptionParametersModel(a, b));
        }

        public Task<int> AddReturnTaskInt(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<int>("Marble.Sandbox.MathService", "AddReturnTaskInt",
                new MathServiceAddReturnTaskIntParametersModel(a, b));
        }

        public Task AddReturnTask(int a, int b)
        {
            return this.messagingClient.CallProcedureAsync("Marble.Sandbox.MathService", "AddReturnTask",
                new MathServiceAddReturnTaskParametersModel(a, b));
        }

        public Task AddReturnVoid(int a, int b)
        {
            return this.messagingClient.CallProcedureAsync("Marble.Sandbox.MathService", "AddReturnVoid",
                new MathServiceAddReturnVoidParametersModel(a, b));
        }

        public Task<MathResult> AddReturnObject(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<MathResult>("Marble.Sandbox.MathService",
                "AddReturnObject", new MathServiceAddReturnObjectParametersModel(a, b));
        }

        public Task<MathResult> AddReturnTaskObject(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<MathResult>("Marble.Sandbox.MathService",
                "AddReturnTaskObject", new MathServiceAddReturnTaskObjectParametersModel(a, b));
        }

        public Task<List<MathResult>> ReturnListTask(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<List<MathResult>>("Marble.Sandbox.MathService",
                "ReturnListTask", new MathServiceReturnListTaskParametersModel(a, b));
        }

        public Task<List<MathResult>> ReturnList(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<List<MathResult>>("Marble.Sandbox.MathService",
                "ReturnList", new MathServiceReturnListParametersModel(a, b));
        }

        public Task<List<int>> ReturnListIntTask(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<List<int>>("Marble.Sandbox.MathService",
                "ReturnListIntTask", new MathServiceReturnListIntTaskParametersModel(a, b));
        }

        public Task<List<int>> ReturnListInt(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<List<int>>("Marble.Sandbox.MathService", "ReturnListInt",
                new MathServiceReturnListIntParametersModel(a, b));
        }

        public Task<Guid> ReturnGuid(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<Guid>("Marble.Sandbox.MathService", "ReturnGuid",
                new MathServiceReturnGuidParametersModel(a, b));
        }

        public Task<Guid?> ReturnNullGuid()
        {
            return this.messagingClient.InvokeProcedureAsync<Guid?>("Marble.Sandbox.MathService", "ReturnNullGuid");
        }

        public Task<MathResult> ReturnNull()
        {
            return this.messagingClient.InvokeProcedureAsync<MathResult>("Marble.Sandbox.MathService", "ReturnNull");
        }

        public Task<MathResult> AddReturnTaskObjectThrowException(int a, int b)
        {
            return this.messagingClient.InvokeProcedureAsync<MathResult>("Marble.Sandbox.MathService",
                "AddReturnTaskObjectThrowException",
                new MathServiceAddReturnTaskObjectThrowExceptionParametersModel(a, b));
        }

        public IObservable<int> StartMathStreamReturnInt(int start)
        {
            return this.messagingClient.InvokeProcedureStream<int>("Marble.Sandbox.MathService",
                "StartMathStreamReturnInt", new MathServiceStartMathStreamReturnIntParametersModel(start));
        }

        public IObservable<MathResult> StartMathStreamReturnObject(int start)
        {
            return this.messagingClient.InvokeProcedureStream<MathResult>("Marble.Sandbox.MathService",
                "StartMathStreamReturnObject", new MathServiceStartMathStreamReturnObjectParametersModel(start));
        }

        public IObservable<MathResult> StartMathStreamReturnObjectThrowException(int start)
        {
            return this.messagingClient.InvokeProcedureStream<MathResult>("Marble.Sandbox.MathService",
                "StartMathStreamReturnObjectThrowException",
                new MathServiceStartMathStreamReturnObjectThrowExceptionParametersModel(start));
        }
    }


    public sealed class MathServiceAddReturnIntParametersModel : ParametersModel
    {
        public MathServiceAddReturnIntParametersModel()
        {
        }

        public MathServiceAddReturnIntParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceAddReturnIntThrowExceptionParametersModel : ParametersModel
    {
        public MathServiceAddReturnIntThrowExceptionParametersModel()
        {
        }

        public MathServiceAddReturnIntThrowExceptionParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceAddReturnTaskIntParametersModel : ParametersModel
    {
        public MathServiceAddReturnTaskIntParametersModel()
        {
        }

        public MathServiceAddReturnTaskIntParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceAddReturnTaskParametersModel : ParametersModel
    {
        public MathServiceAddReturnTaskParametersModel()
        {
        }

        public MathServiceAddReturnTaskParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceAddReturnVoidParametersModel : ParametersModel
    {
        public MathServiceAddReturnVoidParametersModel()
        {
        }

        public MathServiceAddReturnVoidParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceAddReturnObjectParametersModel : ParametersModel
    {
        public MathServiceAddReturnObjectParametersModel()
        {
        }

        public MathServiceAddReturnObjectParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceAddReturnTaskObjectParametersModel : ParametersModel
    {
        public MathServiceAddReturnTaskObjectParametersModel()
        {
        }

        public MathServiceAddReturnTaskObjectParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceReturnListTaskParametersModel : ParametersModel
    {
        public MathServiceReturnListTaskParametersModel()
        {
        }

        public MathServiceReturnListTaskParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceReturnListParametersModel : ParametersModel
    {
        public MathServiceReturnListParametersModel()
        {
        }

        public MathServiceReturnListParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceReturnListIntTaskParametersModel : ParametersModel
    {
        public MathServiceReturnListIntTaskParametersModel()
        {
        }

        public MathServiceReturnListIntTaskParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceReturnListIntParametersModel : ParametersModel
    {
        public MathServiceReturnListIntParametersModel()
        {
        }

        public MathServiceReturnListIntParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceReturnGuidParametersModel : ParametersModel
    {
        public MathServiceReturnGuidParametersModel()
        {
        }

        public MathServiceReturnGuidParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceAddReturnTaskObjectThrowExceptionParametersModel : ParametersModel
    {
        public MathServiceAddReturnTaskObjectThrowExceptionParametersModel()
        {
        }

        public MathServiceAddReturnTaskObjectThrowExceptionParametersModel(int a, int b)
        {
            this.A = a;
            this.B = b;
        }

        public int A { get; set; }
        public int B { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.A,
                this.B
            };
        }
    }


    public sealed class MathServiceStartMathStreamReturnIntParametersModel : ParametersModel
    {
        public MathServiceStartMathStreamReturnIntParametersModel()
        {
        }

        public MathServiceStartMathStreamReturnIntParametersModel(int start)
        {
            this.Start = start;
        }

        public int Start { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.Start
            };
        }
    }


    public sealed class MathServiceStartMathStreamReturnObjectParametersModel : ParametersModel
    {
        public MathServiceStartMathStreamReturnObjectParametersModel()
        {
        }

        public MathServiceStartMathStreamReturnObjectParametersModel(int start)
        {
            this.Start = start;
        }

        public int Start { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.Start
            };
        }
    }


    public sealed class MathServiceStartMathStreamReturnObjectThrowExceptionParametersModel : ParametersModel
    {
        public MathServiceStartMathStreamReturnObjectThrowExceptionParametersModel()
        {
        }

        public MathServiceStartMathStreamReturnObjectThrowExceptionParametersModel(int start)
        {
            this.Start = start;
        }

        public int Start { get; set; }

        public override object[] ToObjectArray()
        {
            return new object[]
            {
                this.Start
            };
        }
    }
}